import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Sri",
      email: "admin1@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Puma",
        logo1: "/image/toys.jpg",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "users@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  womens: [
    {
      name: "Cotton Saree",
      category: "Sarees",
      image: "/images/p12.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Silk Saree",
      category: "Sarees",
      image: "/images/p91.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Apoorva Saree",
      category: "sarees",
      image: "/images/p10.jpg",
      price: 220,
      countInStock: 10,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Material Saree",
      category: "sarees",
      image: "/images/sa4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Kurtha Saree",
      category: "sarees",
      image: "/images/sa5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],

  products: [
    {
      name: "formal shirts",
      category: "shrits",
      image: "/image/p1.jpg",
      price: 820,
      countInStock: 10,
      brand: "Nike",
      rating: 74,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "blue shirts",
      category: "shirts",
      image: "/image/p2.jpg",
      price: 320,
      countInStock: 120,
      brand: "Adidas",
      rating: 44,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "lite-blue shirts",
      category: "shirts",
      image: "/image/p3.jpg",
      price: 620,
      countInStock: 110,
      brand: "Nike",
      rating: 24,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "kack pants",
      category: "pants",
      image: "/image/p4.jpg",
      price: 720,
      countInStock: 10,
      brand: "adidas",
      rating: 14,
      numReviews: 50,
      description: "high quality product",
    },
    {
      name: "formal pant",
      category: "pants",
      image: "/image/p5.jpg",
      price: 920,
      countInStock: 103,
      brand: "adidas",
      rating: 12,
      numReviews: 56,
      description: "high quality product",
    },
    {
      name: "blue pant",
      category: "pant",
      image: "/image/p6.jpg",
      price: 520,
      countInStock: 0,
      brand: "nikos",
      rating: 5,
      numReviews: 18,
      description: "high quality product",
    },
  ],
  tshirts: [
    {
      name: "line t-shirt ",
      category: "Tshirt",
      image: "/image/shirt1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "alvi t-shirt",
      category: "Tshirt",
      image: "/image/shirt2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "yark t-shirt",
      category: "Tshirt",
      image: "/image/shirt3.jpg",
      price: 220,
      countInStock: 10,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "ambar t-shirt",
      category: "Tshirt",
      image: "/image/shirt4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "panku t-shirt",
      category: "Tshirt",
      image: "/image/shirt5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],

  casualshirts: [
    {

      name: 'line casual-shirt',
      category: 'Casual Shirts',
      image: '/image/casual5.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'alvi casual-shirt',
      category: 'casual Shirts',
      image: '/image/casual2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'yark casual-shirt',
      category: 'Casual Shirts',
      image: '/image/casual3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: 'ambar casual-shirt',
      category: 'Casual Shirts',
      image: '/image/casual6.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],

  formalshirts: [
    {
   
      name: 'line formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal6.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
 
      name: 'alvi formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      
      name: 'yark formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      
      name: 'ambar formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },

  ],


  sweaters: [
    {

      name: 'anvi sweater',
      category: 'sweaters',
      image: '/image/sw1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'aruviya sweater',
      category: 'sweaters',
      image: '/image/sw2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'yarky sweater',
      category: 'sweaters',
      image: '/image/sw3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: 'lalachy  sweater',
      category: 'sweater',
      image: '/image/sw4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],

  jackets: [
    {

      name: 'anviy jacket',
      category: 'jacketss',
      image: '/image/ja1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'aruviyas jacket',
      category: 'jackets',
      image: '/image/ja2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'yar jacket',
      category: 'jackets',
      image: '/image/ja3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: 'lalachy  jacket',
      category: 'sweater',
      image: '/image/ja4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],
  blazers: [
    {

      name: 'alvi blazer',
      category: 'blazers',
      image: '/image/bl1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'yogi blazer',
      category: 'blazers',
      image: '/image/bl2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: ' yogo blazer',
      category: 'blazers',
      image: '/image/bl6.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: ' scemy blazer',
      category: 'blazer',
      image: '/image/bl4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {

      name: ' formi blazer',
      category: 'blazer',
      image: '/image/bl5.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],
  suits: [
    {

      name: 'goodes suit',
      category: 'suits',
      image: '/image/suit1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'yogi suit',
      category: 'suits',
      image: '/image/suit2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: ' yahoo suit',
      category: 'suits',
      image: '/image/suit3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: ' scemy suit',
      category: 'suits',
      image: '/image/suit4.jpg',
      price: 978,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {

      name: ' formi suit',
      category: 'suits',
      image: '/image/suit7.jpg',
      price: 578,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],
  rainjackets: [
    {

      name: 'woodes rainjacket',
      category: 'rainjackets',
      image: '/image/rain1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'yogi rainjacket',
      category: 'rainjackets',
      image: '/image/rain2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: ' yahoo rainjacket',
      category: 'rainjackets',
      image: '/image/rain3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: ' scemy rain jacket',
      category: 'rainjackets',
      image: '/image/rain4.jpg',
      price: 578,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    

  ],
  Saree: [
    {
      _id: "7",
      name: "Cotton Saree",
      category: "Saree",
      image: "/images/p12.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "Silk Saree",
      category: "saree",
      image: "/images/p91.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "9",
      name: "Apoorva Saree",
      category: "saree",
      image: "/images/p10.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "10",
      name: "Material Saree",
      category: "saree",
      image: "/images/sa4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "11",
      name: "Kurtha Saree",
      category: "saree",
      image: "/images/sa5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],

  kids: [
    {
      name: "Little Bansi Full Sleeves",
      category: "Kids",
      image: "/images/A2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Pantaloon",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Hansa Inskert",
      category: "Kids",
      image: "/images/kid2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Pantaloon",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Umberalla Harie",
      category: "Kids",
      image: "/images/kid3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Classic Medie",
      category: "Kids",
      image: "/images/kid4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Pantaloon",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Angel Medi",
      category: "Kids",
      image: "/images/kid5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
